backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: events
    label: Events
    folder: content/events
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Featured Image, name: featuredImage, widget: image}

  - name: workshops
    label: Workshops
    folder: content/workshops
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Featured Image, name: featuredImage, widget: image }
      - { label: Body, name: body, widget: markdown }

  - name: testimonials
    label: Testimonials
    folder: content/testimonials
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Customer, name: customer, widget: string }

  - name: blocks
    label: Content Blocks
    files:
      - file: content/blocks/bio.md
        label: Bio
        name: bio
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Profile Picture, name: bioImage, widget: image }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/contact-opening-times.md
        label: Opening Times
        name: opening-iimes
        fields:
          - { label: weight, name: weight, widget: hidden }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/contact-info.md
        label: Contact Info
        name: contact-info
        fields:
          - { label: weight, name: weight, widget: hidden }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/principles-of-reiki.md
        label: Principles of Reiki
        name: principles-of-reiki
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/pricing-readings.md
        label: Pricing Readings
        name: pricing-readings
        fields:
          - { label: weight, name: weight, widget: hidden }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/pricing-reiki-attunement.md
        label: Pricing Reiki Attunement
        name: pricing-reiki-attunement
        fields:
          - { label: weight, name: weight, widget: hidden }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/pricing-spiritual-assessments.md
        label: Pricing Spiritual Assessments
        name: pricing-spiritual-assessments
        fields:
          - { label: weight, name: weight, widget: hidden }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/blocks/pricing-reiki-treatment.md
        label: Pricing Reiki Treatment
        name: pricing-reiki-treatment
        fields:
          - { label: weight, name: weight, widget: hidden }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - file: content/site/home.md
        label: Home Page
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/contact.md
        label: Contact Page
        name: contact
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }

      - file: content/site/pricing.md
        label: Pricing Page
        name: pricing
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }

      - file: content/site/about.md
        label: About Page
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Featured Image, name: featuredImage, widget: image }

      - file: content/site/calendar.md
        label: Events Page
        name: events
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }

      - file: content/site/psychic-spiritual-readings.md
        label: Psychic Spiritual Readings Page
        name: psychic-spiritual-readings
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Featured Image, name: featuredImage, widget: image }

      - file: content/site/reiki-attunement.md
        label: Reiki Attunement Page
        name: reiki-attunement
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Featured Image, name: featuredImage, widget: image }

      - file: content/site/spiritual-assessments.md
        label: Spiritual Assessments Page
        name: spiritual-assessments
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Featured Image, name: featuredImage, widget: image }

      - file: content/site/reiki-healing.md
        label: Reiki Healing Page
        name: reiki-healing
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Featured Image, name: featuredImage, widget: image }

      - file: content/site/teaching.md
        label: Workshop Page
        name: workshop
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Featured Image, name: featuredImage, widget: image }
