backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  # - name: events
  #   label: Events
  #   folder: content/events
  #   create: true
  #   slug: {{year}}-{{month}}-{{day}}-{{slug}}
  #   fields:
  #     - {label: Title, name: title, widget: string}
  #     - {label: Date, name: date, widget: datetime}
  #     - {label: Description, name: description, widget: text}
  #     - {label: Featured Image, name: featuredImage, widget: image}
  #     - {label: Body, name: body, widget: markdown}

  - name: testimonials
    label: Testimonials
    folder: content/testimonials
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Customer, name: customer, widget: string }

  - name: sections
    label: Content Blocks
    files:
      - file: content/site/bio.md
        label: Bio
        name: bio
        fields:
          - { label: Title, name: profileTitle, widget: string }
          - { label: Profile Picture, name: bioImage, widget: image }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/contact-opening-times.md
        label: Opening Times
        name: opening-iimes
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/contact-info.md
        label: Contact Info
        name: contact-info
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/pricing-readings.md
        label: Pricing Readings
        name: pricing-readings
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      
      - file: content/site/pricing-reiki-attunement.md
        label: Pricing Reiki Attunement
        name: pricing-reiki-attunement
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/pricing-reiki-treatment.md
        label: Pricing Reiki Treatment
        name: pricing-reiki-treatment
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - file: content/site/home.md
        label: Home Page
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/contact.md
        label: Contact Page
        name: contact
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }

      - file: content/site/about.md
        label: About Page
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/psychic-spiritual-readings.md
        label: Psychic Spiritual Readings Page
        name: psychic-spiritual-readings
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/reiki-attunement.md
        label: Reiki Attunement Page
        name: reiki-attunement
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }

      - file: content/site/reiki-healing.md
        label: Reiki Healing Page
        name: reiki-healing
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Body, name: body, widget: markdown }
